"""Add mood_checkins table

Revision ID: 3b232f624852
Revises: 8c9eb28a747a
Create Date: 2026-09-27 12:25:51.127678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b232f624852'
down_revision: Union[str, Sequence[str], None] = '8c9eb28a747a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('energy_level', sa.String(length=50), nullable=True),
    sa.Column('sleep_quality', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['menstrual_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_checkins_user_id'), 'mood_checkins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_checkins_user_id'), table_name='mood_checkins')
    op.drop_table('mood_checkins')
    # ### end Alembic commands ###
