"""add_user_demographics

Revision ID: c910808aae93
Revises: cd2c8f63daa8
Create Date: 2026-10-09 00:56:04.438622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c910808aae93'
down_revision: Union[str, Sequence[str], None] = 'cd2c8f63daa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('age_unit', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('patient_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patient_type')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age_unit')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
