"""Add pain_assessments table

Revision ID: ffde0593590b
Revises: b4576b7cfdf7
Create Date: 2026-09-27 02:05:25.863576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffde0593590b'
down_revision: Union[str, Sequence[str], None] = 'b4576b7cfdf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pain_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('body_region', sa.String(length=100), nullable=False),
    sa.Column('pain_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('onset_duration', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('trend', sa.String(length=100), nullable=False),
    sa.Column('associated_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_assessments_user_id'), 'pain_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pain_assessments_user_id'), table_name='pain_assessments')
    op.drop_table('pain_assessments')
    # ### end Alembic commands ###
