import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { consultationApi } from '../api/consultationApi';
import ErrorMessage from '../components/ErrorMessage';
import LoadingSpinner from '../components/LoadingSpinner';
import { Stethoscope, AlertCircle, PhoneCall, FileText, ClipboardList, Plus, Trash2, Calendar, Check, Copy } from 'lucide-react';
import { format, parseISO } from 'date-fns';

const DoctorConsultation = () => {
  const { user } = useAuth();
  const [view, setView] = useState('dashboard'); // dashboard, prep
  const [preps, setPreps] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const [formData, setFormData] = useState({
    main_concern: '',
    symptoms: '',
    questions: '',
    current_medicines: '',
    allergies: ''
  });
  
  // Ephemeral state for guest
  const [guestPrep, setGuestPrep] = useState(null);

  useEffect(() => {
    if (user) {
      loadPreps();
    }
  }, [user]);

  const loadPreps = async () => {
    setLoading(true);
    try {
      const data = await consultationApi.getPreps();
      setPreps(data);
    } catch (err) {
      setError('Failed to load consultation preparations.');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const resetForm = () => {
    setFormData({ main_concern: '', symptoms: '', questions: '', current_medicines: '', allergies: '' });
  };

  const handleSave = async (e) => {
    e.preventDefault();
    if (!formData.main_concern.trim()) {
      setError('Main concern is required.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      if (user) {
        const saved = await consultationApi.createPrep(formData);
        setPreps([saved, ...preps]);
      } else {
        // Guest mode - save to local ephemeral state
        setGuestPrep({
          ...formData,
          id: 'guest-' + Date.now(),
          created_at: new Date().toISOString()
        });
      }
      setView('dashboard');
      resetForm();
    } catch (err) {
      setError('Failed to save consultation preparation.');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Delete this consultation preparation?")) return;
    
    if (!user && id.startsWith('guest-')) {
        setGuestPrep(null);
        return;
    }
    
    try {
      await consultationApi.deletePrep(id);
      setPreps(preps.filter(p => p.id !== id));
    } catch (err) {
      setError('Failed to delete preparation.');
    }
  };

  const generateSummary = (prep) => {
    let summary = `CONSULTATION PREPARATION\nDate: ${format(parseISO(prep.created_at), 'PPP')}\n\n`;
    summary += `MAIN CONCERN:\n${prep.main_concern}\n\n`;
    
    if (prep.symptoms?.trim()) {
      summary += `SYMPTOMS & ONSET:\n${prep.symptoms}\n\n`;
    }
    
    if (prep.current_medicines?.trim()) {
      summary += `CURRENT MEDICINES:\n${prep.current_medicines}\n\n`;
    }
    
    if (prep.allergies?.trim()) {
      summary += `ALLERGIES:\n${prep.allergies}\n\n`;
    }
    
    if (prep.questions?.trim()) {
      summary += `QUESTIONS FOR DOCTOR:\n${prep.questions}\n\n`;
    }
    
    summary += `(Generated by AI Medical Symptom Checker. This information is self-reported by the user.)`;
    return summary;
  };

  const handleCopy = (prep) => {
    const text = generateSummary(prep);
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <div className="mb-8 text-center">
        <h1 className="text-3xl font-bold text-teal-800 flex justify-center items-center gap-2">
          <Stethoscope className="w-8 h-8 text-teal-600" /> Doctor Consultation & Telemedicine
        </h1>
        <p className="text-slate-600 mt-2 max-w-2xl mx-auto">
          Prepare for your upcoming visit and manage your medical summaries.
        </p>
      </div>

      <ErrorMessage message={error} />

      {/* Emergency Notice */}
      <div className="bg-red-50 border-l-4 border-red-600 p-6 rounded-r-xl mb-8 shadow-sm flex items-start gap-4">
        <PhoneCall className="w-8 h-8 text-red-600 shrink-0 mt-1" />
        <div>
          <h2 className="text-xl font-bold text-red-800 mb-1">Medical Emergency</h2>
          <p className="text-red-700 font-medium">
            If you are experiencing a medical emergency, severe pain, or difficulty breathing, please contact emergency services immediately.
          </p>
          <div className="mt-3 bg-white inline-block px-4 py-2 rounded-lg border border-red-200 text-red-800 font-bold">
            For India, dial 112
          </div>
          <p className="text-sm text-red-600 mt-2 italic">
            This app does not contact emergency services for you and does not provide clinical care.
          </p>
        </div>
      </div>

      {view === 'dashboard' && (
        <div className="space-y-8">
          
          {/* Find a Doctor Placeholder */}
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="bg-slate-50 border-b border-slate-200 px-6 py-4">
              <h2 className="text-xl font-bold text-slate-800">Find a Doctor / Telemedicine</h2>
            </div>
            <div className="p-6">
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-5 flex items-start gap-3">
                <AlertCircle className="w-6 h-6 text-blue-600 shrink-0" />
                <div>
                  <h3 className="font-bold text-blue-900 mb-1">Prototype Notice</h3>
                  <p className="text-blue-800 text-sm">
                    This module is currently a prototype. Real-time doctor bookings, clinic directories, and telemedicine video calls are not available in this version. In the future, this section will integrate with verified third-party healthcare networks to provide real-time appointments.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Consultation Preparation */}
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="bg-slate-50 border-b border-slate-200 px-6 py-4 flex justify-between items-center">
              <h2 className="text-xl font-bold text-slate-800">Consultation Summaries</h2>
              <button 
                onClick={() => setView('prep')} 
                className="bg-teal-600 text-white px-4 py-2 rounded-lg font-bold hover:bg-teal-700 flex items-center gap-2 text-sm"
              >
                <Plus className="w-4 h-4" /> New Preparation
              </button>
            </div>
            
            <div className="p-6">
              {!user && (
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6 text-sm text-yellow-800 flex items-start gap-2">
                  <AlertCircle className="w-5 h-5 flex-shrink-0" />
                  <div>You are using Guest Mode. You can create a temporary consultation summary, but it will not be permanently saved.</div>
                </div>
              )}

              {loading ? (
                <LoadingSpinner />
              ) : (preps.length === 0 && !guestPrep) ? (
                <div className="text-center py-10 text-slate-500">
                  <ClipboardList className="w-12 h-12 mx-auto text-slate-300 mb-3" />
                  <p>You haven't prepared any consultation summaries yet.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {guestPrep && (
                    <div className="border border-yellow-300 bg-yellow-50/30 rounded-xl p-5 relative">
                      <div className="absolute top-4 right-4 bg-yellow-200 text-yellow-800 text-xs font-bold px-2 py-1 rounded">GUEST (UNSAVED)</div>
                      <div className="flex items-center gap-2 text-slate-500 text-sm mb-3 font-medium">
                        <Calendar className="w-4 h-4" /> {format(parseISO(guestPrep.created_at), 'PPP')}
                      </div>
                      <h3 className="font-bold text-slate-800 text-lg mb-2 line-clamp-1">{guestPrep.main_concern}</h3>
                      <p className="text-slate-600 text-sm mb-4 line-clamp-2">{guestPrep.symptoms || 'No symptoms specified'}</p>
                      
                      <div className="flex gap-2 mt-4 pt-4 border-t border-yellow-200">
                        <button onClick={() => handleCopy(guestPrep)} className="flex-1 bg-white border border-slate-300 text-slate-700 py-2 rounded-lg text-sm font-semibold hover:bg-slate-50 flex justify-center items-center gap-2">
                          {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />} Copy Summary
                        </button>
                        <button onClick={() => handleDelete(guestPrep.id)} className="px-3 border border-red-200 text-red-600 py-2 rounded-lg text-sm hover:bg-red-50">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  )}

                  {preps.map(prep => (
                    <div key={prep.id} className="border border-slate-200 rounded-xl p-5 hover:shadow-md transition-shadow">
                      <div className="flex items-center gap-2 text-slate-500 text-sm mb-3 font-medium">
                        <Calendar className="w-4 h-4" /> {format(parseISO(prep.created_at), 'PPP')}
                      </div>
                      <h3 className="font-bold text-slate-800 text-lg mb-2 line-clamp-1">{prep.main_concern}</h3>
                      <p className="text-slate-600 text-sm mb-4 line-clamp-2">{prep.symptoms || 'No symptoms specified'}</p>
                      
                      <div className="flex gap-2 mt-4 pt-4 border-t border-slate-100">
                        <button onClick={() => handleCopy(prep)} className="flex-1 bg-white border border-slate-300 text-slate-700 py-2 rounded-lg text-sm font-semibold hover:bg-slate-50 flex justify-center items-center gap-2">
                          {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />} Copy Summary
                        </button>
                        <button onClick={() => handleDelete(prep.id)} className="px-3 border border-red-200 text-red-600 py-2 rounded-lg text-sm hover:bg-red-50">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {view === 'prep' && (
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 md:p-8">
          <div className="flex items-center gap-3 mb-6">
            <FileText className="w-6 h-6 text-teal-600" />
            <h2 className="text-2xl font-bold text-slate-800">Prepare Consultation Summary</h2>
          </div>
          
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6 text-sm text-blue-800">
            <strong>Privacy Note:</strong> This form helps you organize your thoughts for a doctor visit. Your data is not automatically sent to any external doctor or clinic. You are fully in control of sharing this summary.
          </div>

          <form onSubmit={handleSave} className="space-y-6">
            <div>
              <label className="block text-sm font-bold text-slate-700 mb-2">Main Concern / Reason for Visit *</label>
              <input 
                type="text" name="main_concern" required value={formData.main_concern} onChange={handleInputChange}
                className="w-full p-3 border border-slate-300 rounded-lg focus:ring-teal-500 focus:border-teal-500" 
                placeholder="e.g. Persistent lower back pain" 
              />
            </div>
            
            <div>
              <label className="block text-sm font-bold text-slate-700 mb-2">Symptoms & Onset (Optional)</label>
              <textarea 
                name="symptoms" value={formData.symptoms} onChange={handleInputChange}
                className="w-full p-3 border border-slate-300 rounded-lg h-24 resize-none" 
                placeholder="Detail what you're feeling and when it started." 
              />
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-bold text-slate-700 mb-2">Current Medicines (Optional)</label>
                <textarea 
                  name="current_medicines" value={formData.current_medicines} onChange={handleInputChange}
                  className="w-full p-3 border border-slate-300 rounded-lg h-24 resize-none" 
                  placeholder="List any prescriptions or supplements." 
                />
              </div>
              <div>
                <label className="block text-sm font-bold text-slate-700 mb-2">Allergies (Optional)</label>
                <textarea 
                  name="allergies" value={formData.allergies} onChange={handleInputChange}
                  className="w-full p-3 border border-slate-300 rounded-lg h-24 resize-none" 
                  placeholder="List any known allergies to drugs or food." 
                />
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-bold text-slate-700 mb-2">Questions for the Doctor (Optional)</label>
              <textarea 
                name="questions" value={formData.questions} onChange={handleInputChange}
                className="w-full p-3 border border-slate-300 rounded-lg h-24 resize-none" 
                placeholder="What do you want to make sure you ask during the visit?" 
              />
            </div>

            <div className="flex gap-4 pt-4 border-t border-slate-200">
              <button type="button" onClick={() => {setView('dashboard'); resetForm();}} className="py-3 px-6 rounded-lg bg-slate-100 text-slate-700 font-semibold hover:bg-slate-200 transition-colors">
                Cancel
              </button>
              <button type="submit" disabled={loading} className="flex-1 bg-teal-600 text-white font-bold py-3 px-4 rounded-lg hover:bg-teal-700 transition-colors flex justify-center items-center">
                {loading ? 'Saving...' : (user ? 'Save Consultation Prep' : 'Create Temporary Summary')}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};

export default DoctorConsultation;
